## Spectral-Group Dropout: Validation Selection and Fixed-Mask Experiment

In [3]:
from satx.engine import fit, load_training_config
from satx.utils.paths import resolve_project_path

def run_frozen_config(config_path):
    config = load_training_config(config_path)
    print(config)
    print("Run name:", config.run_name)
    print("Output:", config.run_dir())

    history = fit(config)

    print("Training complete")
    print("Best epoch:", history["best_epoch"])
    print("Best validation macro-F1:", history["best_val_macro_f1"])
    print(
        "Validation accuracy at best macro-F1 epoch:",
        history["best_val_accuracy"],
    )
    counts = history["epochs"][0]["train"]["mask_counts"]

    if counts is not None:
        total = sum(counts.values())
        masked_ratio = 1.0 - counts["NONE"] / total

        print(counts)
        print("Total samples:", total)
        print("Observed masked ratio:", masked_ratio)
    else:
        print("Spectral dropout was not enabled.")

    return history

In [2]:
baseline_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_baseline.yaml")
)

TrainingConfig(modality='ms', split_type='spatial', data_dir='./data', splits_dir='./splits_data', output_dir='./outputs/runs', model_input_mode='direct', num_classes=10, pretrained=True, normalization='zscore', group_dropout_p=0.0, dropout_seed=42, epochs=20, batch_size=32, num_workers=4, learning_rate=0.0001, weight_decay=0.001, seed=42, device='auto', pin_memory=True)
Run name: resnet50_ms_spatial_direct_pretrained_zscore_seed42
Output: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/outputs/runs/resnet50_ms_spatial_direct_pretrained_zscore_seed42
Starting run: resnet50_ms_spatial_direct_pretrained_zscore_seed42
Device: cuda
Epochs: 20
Batch size: 32

Epoch 01/20
  train loss=0.4838 acc=0.8554
  val   loss=0.1769 acc=0.9443 macro_f1=0.9176
  best val macro_f1=0.9176

Epoch 02/20
  train loss=0.1056 acc=0.9669
  val   loss=0.1667 acc=0.9428 macro_f1=0.9130
  best val macro_f1=0.9176

Epoch 03/20
  train loss=0.0520 acc=0.9832
  val   loss=0.1329 acc=0.9589 macro_f1=0.9387
  best val macro_f1=0.9387

Epoch 04/20
  train loss=0.0455 acc=0.9857
  val   loss=0.1452 acc=0.9554 macro_f1=0.9298
  best val macro_f1=0.9387

Epoch 05/20
  train loss=0.0293 acc=0.9907
  val   loss=0.3846 acc=0.8369 macro_f1=0.8582
  best val macro_f1=0.9387

Epoch 06/20
  train loss=0.0285 acc=0.9912
  val   loss=0.2791 acc=0.8965 macro_f1=0.8850
  best val macro_f1=0.9387

Epoch 07/20
  train loss=0.0218 acc=0.9937
  val   loss=0.1644 acc=0.9513 macro_f1=0.9279
  best val macro_f1=0.9387

Epoch 08/20
  train loss=0.0182 acc=0.9944
  val   loss=0.2104 acc=0.9370 macro_f1=0.9019
  best val macro_f1=0.9387

Epoch 09/20
  train loss=0.0149 acc=0.9949
  val   loss=0.1768 acc=0.9539 macro_f1=0.9322
  best val macro_f1=0.9387

Epoch 10/20
  train loss=0.0199 acc=0.9940
  val   loss=0.1730 acc=0.9519 macro_f1=0.9249
  best val macro_f1=0.9387

Epoch 11/20
  train loss=0.0179 acc=0.9943
  val   loss=0.1727 acc=0.9552 macro_f1=0.9305
  best val macro_f1=0.9387

Epoch 12/20
  train loss=0.0162 acc=0.9954
  val   loss=0.8556 acc=0.8481 macro_f1=0.8620
  best val macro_f1=0.9387

Epoch 13/20
  train loss=0.0139 acc=0.9954
  val   loss=0.4193 acc=0.8315 macro_f1=0.8502
  best val macro_f1=0.9387

Epoch 14/20
  train loss=0.0135 acc=0.9958
  val   loss=0.1657 acc=0.9550 macro_f1=0.9305
  best val macro_f1=0.9387

Epoch 15/20
  train loss=0.0114 acc=0.9959
  val   loss=0.4861 acc=0.8780 macro_f1=0.8805
  best val macro_f1=0.9387

Epoch 16/20
  train loss=0.0067 acc=0.9980
  val   loss=1.0757 acc=0.8337 macro_f1=0.8643
  best val macro_f1=0.9387

Epoch 17/20
  train loss=0.0098 acc=0.9970
  val   loss=0.2100 acc=0.9446 macro_f1=0.9157
  best val macro_f1=0.9387

Epoch 18/20
  train loss=0.0100 acc=0.9965
  val   loss=0.5559 acc=0.8681 macro_f1=0.8733
  best val macro_f1=0.9387

Epoch 19/20
  train loss=0.0107 acc=0.9967
  val   loss=0.2299 acc=0.9357 macro_f1=0.9005
  best val macro_f1=0.9387

Epoch 20/20
  train loss=0.0123 acc=0.9960
  val   loss=0.9708 acc=0.8643 macro_f1=0.8864
  best val macro_f1=0.9387

Training complete
Best epoch: 3
Best validation macro-F1: 0.9387348709670127
Validation accuracy at best macro-F1 epoch: 0.9588888888888889
Spectral dropout was not enabled.

COMMIT 0 Stage - Baseline with p=0.1, 0.3, 0.5

In [3]:
p10_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p10.yaml")
)

TrainingConfig(modality='ms', split_type='spatial', data_dir='./data', splits_dir='./splits_data', output_dir='./outputs/runs', model_input_mode='direct', num_classes=10, pretrained=True, normalization='zscore', group_dropout_p=0.1, dropout_seed=42, epochs=20, batch_size=32, num_workers=4, learning_rate=0.0001, weight_decay=0.001, seed=42, device='auto', pin_memory=True)
Run name: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p10_dseed42
Output: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/outputs/runs/resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p10_dseed42
Starting run: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p10_dseed42
Device: cuda
Epochs: 20
Batch size: 32

Epoch 01/20
  train loss=0.4993 acc=0.8496
  val   loss=0.1520 acc=0.9530 macro_f1=0.9303
  best val macro_f1=0.9303

Epoch 02/20
  train loss=0.1192 acc=0.9630
  val   loss=0.1530 acc=0.9459 macro_f1=0.9128
  best val macro_f1=0.9303

Epoch 03/20
  train loss=0.0661 acc=0.9791
  val   loss=0.1495 acc=0.9517 macro_f1=0.9252
  best val macro_f1=0.9303

Epoch 04/20
  train loss=0.0504 acc=0.9840
  val   loss=0.1488 acc=0.9539 macro_f1=0.9290
  best val macro_f1=0.9303

Epoch 05/20
  train loss=0.0440 acc=0.9866
  val   loss=0.2067 acc=0.9319 macro_f1=0.9029
  best val macro_f1=0.9303

Epoch 06/20
  train loss=0.0392 acc=0.9887
  val   loss=4.8288 acc=0.7898 macro_f1=0.8380
  best val macro_f1=0.9303

Epoch 07/20
  train loss=0.0315 acc=0.9893
  val   loss=0.2784 acc=0.8978 macro_f1=0.8816
  best val macro_f1=0.9303

Epoch 08/20
  train loss=0.0256 acc=0.9917
  val   loss=0.2584 acc=0.9089 macro_f1=0.9018
  best val macro_f1=0.9303

Epoch 09/20
  train loss=0.0293 acc=0.9911
  val   loss=0.1439 acc=0.9554 macro_f1=0.9311
  best val macro_f1=0.9311

Epoch 10/20
  train loss=0.0215 acc=0.9935
  val   loss=0.1330 acc=0.9630 macro_f1=0.9452
  best val macro_f1=0.9452

Epoch 11/20
  train loss=0.0250 acc=0.9925
  val   loss=1.4481 acc=0.8531 macro_f1=0.8762
  best val macro_f1=0.9452

Epoch 12/20
  train loss=0.0228 acc=0.9925
  val   loss=0.7300 acc=0.8663 macro_f1=0.8918
  best val macro_f1=0.9452

Epoch 13/20
  train loss=0.0194 acc=0.9946
  val   loss=8.9247 acc=0.7756 macro_f1=0.8241
  best val macro_f1=0.9452

Epoch 14/20
  train loss=0.0194 acc=0.9941
  val   loss=0.1841 acc=0.9498 macro_f1=0.9272
  best val macro_f1=0.9452

Epoch 15/20
  train loss=0.0176 acc=0.9944
  val   loss=0.2289 acc=0.9422 macro_f1=0.9191
  best val macro_f1=0.9452

Epoch 16/20
  train loss=0.0152 acc=0.9954
  val   loss=0.1309 acc=0.9644 macro_f1=0.9454
  best val macro_f1=0.9454

Epoch 17/20
  train loss=0.0151 acc=0.9950
  val   loss=0.1494 acc=0.9548 macro_f1=0.9304
  best val macro_f1=0.9454

Epoch 18/20
  train loss=0.0167 acc=0.9949
  val   loss=0.1476 acc=0.9581 macro_f1=0.9369
  best val macro_f1=0.9454

Epoch 19/20
  train loss=0.0153 acc=0.9951
  val   loss=0.1971 acc=0.9515 macro_f1=0.9275
  best val macro_f1=0.9454

Epoch 20/20
  train loss=0.0163 acc=0.9953
  val   loss=0.2080 acc=0.9413 macro_f1=0.9128
  best val macro_f1=0.9454

Training complete
Best epoch: 16
Best validation macro-F1: 0.9454068217184585
Validation accuracy at best macro-F1 epoch: 0.9644444444444444
{'NONE': 14588, 'VISIBLE': 388, 'RED_EDGE_NIR': 418, 'ATMOSPHERIC': 387, 'SWIR': 419}
Total samples: 16200
Observed masked ratio: 0.09950617283950614

In [4]:
p30_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p30.yaml")
)

TrainingConfig(modality='ms', split_type='spatial', data_dir='./data', splits_dir='./splits_data', output_dir='./outputs/runs', model_input_mode='direct', num_classes=10, pretrained=True, normalization='zscore', group_dropout_p=0.3, dropout_seed=42, epochs=20, batch_size=32, num_workers=4, learning_rate=0.0001, weight_decay=0.001, seed=42, device='auto', pin_memory=True)
Run name: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p30_dseed42
Output: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/outputs/runs/resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p30_dseed42
Starting run: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p30_dseed42
Device: cuda
Epochs: 20
Batch size: 32

Epoch 01/20
  train loss=0.5251 acc=0.8409
  val   loss=0.1701 acc=0.9461 macro_f1=0.9191
  best val macro_f1=0.9191

Epoch 02/20
  train loss=0.1363 acc=0.9559
  val   loss=0.1547 acc=0.9463 macro_f1=0.9203
  best val macro_f1=0.9203

Epoch 03/20
  train loss=0.0791 acc=0.9740
  val   loss=0.2824 acc=0.8878 macro_f1=0.8857
  best val macro_f1=0.9203

Epoch 04/20
  train loss=0.0655 acc=0.9790
  val   loss=0.1428 acc=0.9567 macro_f1=0.9339
  best val macro_f1=0.9339

Epoch 05/20
  train loss=0.0488 acc=0.9832
  val   loss=0.1487 acc=0.9522 macro_f1=0.9293
  best val macro_f1=0.9339

Epoch 06/20
  train loss=0.0465 acc=0.9847
  val   loss=0.3391 acc=0.8567 macro_f1=0.8631
  best val macro_f1=0.9339

Epoch 07/20
  train loss=0.0382 acc=0.9877
  val   loss=0.3024 acc=0.9102 macro_f1=0.9036
  best val macro_f1=0.9339

Epoch 08/20
  train loss=0.0338 acc=0.9901
  val   loss=0.4477 acc=0.8550 macro_f1=0.8684
  best val macro_f1=0.9339

Epoch 09/20
  train loss=0.0294 acc=0.9909
  val   loss=0.1885 acc=0.9422 macro_f1=0.9129
  best val macro_f1=0.9339

Epoch 10/20
  train loss=0.0320 acc=0.9899
  val   loss=0.1402 acc=0.9567 macro_f1=0.9305
  best val macro_f1=0.9339

Epoch 11/20
  train loss=0.0337 acc=0.9888
  val   loss=0.2447 acc=0.9143 macro_f1=0.9034
  best val macro_f1=0.9339

Epoch 12/20
  train loss=0.0249 acc=0.9923
  val   loss=0.1375 acc=0.9569 macro_f1=0.9314
  best val macro_f1=0.9339

Epoch 13/20
  train loss=0.0210 acc=0.9931
  val   loss=1.9494 acc=0.8098 macro_f1=0.8502
  best val macro_f1=0.9339

Epoch 14/20
  train loss=0.0254 acc=0.9920
  val   loss=0.1651 acc=0.9543 macro_f1=0.9265
  best val macro_f1=0.9339

Epoch 15/20
  train loss=0.0219 acc=0.9936
  val   loss=0.1321 acc=0.9626 macro_f1=0.9448
  best val macro_f1=0.9448

Epoch 16/20
  train loss=0.0234 acc=0.9928
  val   loss=0.1612 acc=0.9520 macro_f1=0.9312
  best val macro_f1=0.9448

Epoch 17/20
  train loss=0.0205 acc=0.9938
  val   loss=0.2744 acc=0.9285 macro_f1=0.8934
  best val macro_f1=0.9448

Epoch 18/20
  train loss=0.0175 acc=0.9941
  val   loss=0.2104 acc=0.9430 macro_f1=0.9125
  best val macro_f1=0.9448

Epoch 19/20
  train loss=0.0161 acc=0.9953
  val   loss=0.1740 acc=0.9550 macro_f1=0.9285
  best val macro_f1=0.9448

Epoch 20/20
  train loss=0.0162 acc=0.9949
  val   loss=0.1806 acc=0.9578 macro_f1=0.9314
  best val macro_f1=0.9448

Training complete
Best epoch: 15
Best validation macro-F1: 0.9447699298502675
Validation accuracy at best macro-F1 epoch: 0.9625925925925926
{'NONE': 11319, 'VISIBLE': 1187, 'RED_EDGE_NIR': 1246, 'ATMOSPHERIC': 1203, 'SWIR': 1245}
Total samples: 16200
Observed masked ratio: 0.3012962962962963

In [7]:
p50_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p50.yaml")
)

TrainingConfig(modality='ms', split_type='spatial', data_dir='./data', splits_dir='./splits_data', output_dir='./outputs/runs', model_input_mode='direct', num_classes=10, pretrained=True, normalization='zscore', group_dropout_p=0.5, dropout_seed=42, epochs=20, batch_size=32, num_workers=4, learning_rate=0.0001, weight_decay=0.001, seed=42, device='auto', pin_memory=True)
Run name: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p50_dseed42
Output: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/outputs/runs/resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p50_dseed42
Starting run: resnet50_ms_spatial_direct_pretrained_zscore_seed42_drop_p50_dseed42
Device: cuda
Epochs: 20
Batch size: 32

Epoch 01/20
  train loss=0.5376 acc=0.8335
  val   loss=0.1881 acc=0.9415 macro_f1=0.9157
  best val macro_f1=0.9157

Epoch 02/20
  train loss=0.1521 acc=0.9509
  val   loss=0.1543 acc=0.9476 macro_f1=0.9192
  best val macro_f1=0.9192

Epoch 03/20
  train loss=0.0999 acc=0.9664
  val   loss=0.3163 acc=0.8498 macro_f1=0.8543
  best val macro_f1=0.9192

Epoch 04/20
  train loss=0.0766 acc=0.9754
  val   loss=0.2278 acc=0.8969 macro_f1=0.8942
  best val macro_f1=0.9192

Epoch 05/20
  train loss=0.0615 acc=0.9810
  val   loss=0.1421 acc=0.9526 macro_f1=0.9303
  best val macro_f1=0.9303

Epoch 06/20
  train loss=0.0523 acc=0.9832
  val   loss=0.7792 acc=0.8094 macro_f1=0.8454
  best val macro_f1=0.9303

Epoch 07/20
  train loss=0.0447 acc=0.9857
  val   loss=0.1702 acc=0.9476 macro_f1=0.9258
  best val macro_f1=0.9303

Epoch 08/20
  train loss=0.0399 acc=0.9866
  val   loss=0.1401 acc=0.9552 macro_f1=0.9341
  best val macro_f1=0.9341

Epoch 09/20
  train loss=0.0357 acc=0.9894
  val   loss=0.1539 acc=0.9526 macro_f1=0.9319
  best val macro_f1=0.9341

Epoch 10/20
  train loss=0.0357 acc=0.9877
  val   loss=0.1411 acc=0.9581 macro_f1=0.9357
  best val macro_f1=0.9357

Epoch 11/20
  train loss=0.0310 acc=0.9893
  val   loss=0.1440 acc=0.9598 macro_f1=0.9408
  best val macro_f1=0.9408

Epoch 12/20
  train loss=0.0306 acc=0.9893
  val   loss=0.1744 acc=0.9496 macro_f1=0.9191
  best val macro_f1=0.9408

Epoch 13/20
  train loss=0.0222 acc=0.9929
  val   loss=0.1296 acc=0.9626 macro_f1=0.9432
  best val macro_f1=0.9432

Epoch 14/20
  train loss=0.0297 acc=0.9904
  val   loss=0.1496 acc=0.9589 macro_f1=0.9388
  best val macro_f1=0.9432

Epoch 15/20
  train loss=0.0223 acc=0.9930
  val   loss=0.1717 acc=0.9481 macro_f1=0.9221
  best val macro_f1=0.9432

Epoch 16/20
  train loss=0.0211 acc=0.9933
  val   loss=0.1406 acc=0.9602 macro_f1=0.9416
  best val macro_f1=0.9432

Epoch 17/20
  train loss=0.0221 acc=0.9927
  val   loss=0.1400 acc=0.9615 macro_f1=0.9398
  best val macro_f1=0.9432

Epoch 18/20
  train loss=0.0195 acc=0.9939
  val   loss=0.1596 acc=0.9528 macro_f1=0.9308
  best val macro_f1=0.9432

Epoch 19/20
  train loss=0.0207 acc=0.9931
  val   loss=0.1287 acc=0.9670 macro_f1=0.9498
  best val macro_f1=0.9498

Epoch 20/20
  train loss=0.0198 acc=0.9941
  val   loss=0.2065 acc=0.9400 macro_f1=0.9145
  best val macro_f1=0.9498

Training complete
Best epoch: 19
Best validation macro-F1: 0.9498020121354424
Validation accuracy at best macro-F1 epoch: 0.967037037037037
{'NONE': 8098, 'VISIBLE': 1977, 'RED_EDGE_NIR': 2099, 'ATMOSPHERIC': 1984, 'SWIR': 2042}
Total samples: 16200
Observed masked ratio: 0.5001234567901234

In [ ]:
p70_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p70.yaml")
)

In [ ]:
p90_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p90.yaml")
)

In [ ]:
p100_history = run_frozen_config(
    resolve_project_path("configs/ms_spatial_dropout_p100.yaml")
)

In [4]:
import json
import subprocess
from pathlib import Path
import pandas as pd

from satx.engine import load_training_config


CONFIG_PATHS = {
    "MS_SPATIAL_DROP_BASELINE": resolve_project_path("configs/ms_spatial_dropout_baseline.yaml"),
    "MS_SPATIAL_DROP_P01": resolve_project_path("configs/ms_spatial_dropout_p10.yaml"),
    "MS_SPATIAL_DROP_P03": resolve_project_path("configs/ms_spatial_dropout_p30.yaml"),
    "MS_SPATIAL_DROP_P05": resolve_project_path("configs/ms_spatial_dropout_p50.yaml"),
    "MS_SPATIAL_DROP_P07": resolve_project_path("configs/ms_spatial_dropout_p70.yaml"),
    "MS_SPATIAL_DROP_P09": resolve_project_path("configs/ms_spatial_dropout_p90.yaml"),
    "MS_SPATIAL_DROP_P10": resolve_project_path("configs/ms_spatial_dropout_p100.yaml"),
}

git_hash = subprocess.check_output(
    ["git", "rev-parse", "HEAD"],
    text=True,
).strip()

summary_rows = []
epoch_rows = []

for run_id, config_path in CONFIG_PATHS.items():
    config = load_training_config(config_path)
    run_dir = config.run_dir()
    history_path = run_dir / "metrics_history.json"
    checkpoint_path = run_dir / "best.pt"

    history = json.loads(history_path.read_text(encoding="utf-8"))

    summary_rows.append(
        {
            "run_id": run_id,
            "protocol": "spatial",
            "modality": "ms",
            "group_dropout_p": config.group_dropout_p,
            "dropout_seed": config.dropout_seed,
            "training_seed": config.seed,
            "best_epoch": history["best_epoch"],
            "best_val_accuracy": history["best_val_accuracy"],
            "best_val_macro_f1": history["best_val_macro_f1"],
            "config_path": config_path,
            "checkpoint_path": str(checkpoint_path),
            "metrics_path": str(history_path),
            "git_hash": git_hash,
            "status": "complete",
        }
    )

    for epoch_record in history["epochs"]:
        counts = epoch_record["train"].get("mask_counts") or {}
        epoch_rows.append(
            {
                "run_id": run_id,
                "group_dropout_p": config.group_dropout_p,
                "epoch": epoch_record["epoch"],
                "train_loss": epoch_record["train"]["loss"],
                "train_accuracy": epoch_record["train"]["accuracy"],
                "val_loss": epoch_record["val"]["loss"],
                "val_accuracy": epoch_record["val"]["accuracy"],
                "val_macro_f1": epoch_record["val"]["macro_f1"],
                "mask_none": counts.get("NONE", 0),
                "mask_visible": counts.get("VISIBLE", 0),
                "mask_red_edge_nir": counts.get("RED_EDGE_NIR", 0),
                "mask_atmospheric": counts.get("ATMOSPHERIC", 0),
                "mask_swir": counts.get("SWIR", 0),
            }
        )

results_dir = resolve_project_path("results/drop_out_experiment")
results_dir.mkdir(exist_ok=True)

summary_df = pd.DataFrame(summary_rows)
epoch_df = pd.DataFrame(epoch_rows)

summary_df.to_csv(
    results_dir / "w3_dropout_validation_summary.csv",
    index=False,
)
epoch_df.to_csv(
    results_dir / "w3_dropout_epoch_history.csv",
    index=False,
)

summary_df

,run_id,protocol,modality,group_dropout_p,dropout_seed,training_seed,best_epoch,best_val_accuracy,best_val_macro_f1,config_path,checkpoint_path,metrics_path,git_hash,status
0,MS_SPATIAL_DROP_BASELINE,spatial,ms,0.0,42,42,3,0.958889,0.938735,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
1,MS_SPATIAL_DROP_P01,spatial,ms,0.1,42,42,16,0.964444,0.945407,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
2,MS_SPATIAL_DROP_P03,spatial,ms,0.3,42,42,15,0.962593,0.944770,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
3,MS_SPATIAL_DROP_P05,spatial,ms,0.5,42,42,19,0.967037,0.949802,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
4,MS_SPATIAL_DROP_P07,spatial,ms,0.7,42,42,19,0.961296,0.939807,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
5,MS_SPATIAL_DROP_P09,spatial,ms,0.9,42,42,19,0.960370,0.940926,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete
6,MS_SPATIAL_DROP_P10,spatial,ms,1.0,42,42,18,0.960926,0.938576,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,/home/windhurt/dl_projects/projects/satx-euros...,f708e9a66ca889deda08838649a3424a8dacaeaf,complete

Select Best Candidate

In [5]:
FORMAL_RUN_IDS = [
    "MS_SPATIAL_DROP_BASELINE",
    "MS_SPATIAL_DROP_P01",
    "MS_SPATIAL_DROP_P03",
    "MS_SPATIAL_DROP_P05",
    "MS_SPATIAL_DROP_P07",
    "MS_SPATIAL_DROP_P09",
    "MS_SPATIAL_DROP_P10",
]

baseline_row = (summary_df[summary_df["run_id"] == "MS_SPATIAL_DROP_BASELINE"].iloc[0])

dropout_candidates = (
    summary_df[
        summary_df["run_id"].isin(
            [
                "MS_SPATIAL_DROP_P01",
                "MS_SPATIAL_DROP_P03",
                "MS_SPATIAL_DROP_P05",
                "MS_SPATIAL_DROP_P07",
                "MS_SPATIAL_DROP_P09",
                "MS_SPATIAL_DROP_P10",
            ]
        )
    ]
    .sort_values(
        ["best_val_macro_f1", "group_dropout_p"],
        ascending=[False, True],
        kind="mergesort",
    )
)

selected_row = dropout_candidates.iloc[0]

display(
    dropout_candidates[
        [
            "run_id",
            "group_dropout_p",
            "best_epoch",
            "best_val_accuracy",
            "best_val_macro_f1",
            "checkpoint_path",
        ]
    ]
)

print("Selected dropout model:", selected_row["run_id"])
print("Selected p:", selected_row["group_dropout_p"])
print(
    "Selection validation macro-F1:",
    selected_row["best_val_macro_f1"],
)

,run_id,group_dropout_p,best_epoch,best_val_accuracy,best_val_macro_f1,checkpoint_path
3,MS_SPATIAL_DROP_P05,0.5,19,0.967037,0.949802,/home/windhurt/dl_projects/projects/satx-euros...
1,MS_SPATIAL_DROP_P01,0.1,16,0.964444,0.945407,/home/windhurt/dl_projects/projects/satx-euros...
2,MS_SPATIAL_DROP_P03,0.3,15,0.962593,0.944770,/home/windhurt/dl_projects/projects/satx-euros...
5,MS_SPATIAL_DROP_P09,0.9,19,0.960370,0.940926,/home/windhurt/dl_projects/projects/satx-euros...
4,MS_SPATIAL_DROP_P07,0.7,19,0.961296,0.939807,/home/windhurt/dl_projects/projects/satx-euros...
6,MS_SPATIAL_DROP_P10,1.0,18,0.960926,0.938576,/home/windhurt/dl_projects/projects/satx-euros...

Selected dropout model: MS_SPATIAL_DROP_P05
Selected p: 0.5
Selection validation macro-F1: 0.9498020121354424

In [6]:
import numpy as np
import torch

from sklearn.metrics import accuracy_score, f1_score

from satx.data import CLASS_NAMES
from satx.engine import TrainingConfig, resolve_device, set_seed
from satx.engine.data import build_test_dataloader
from satx.eval.fixed_group_mask import apply_fixed_group_mask
from satx.models import build_resnet50


def load_best_model_from_row(run_row):
    """Load and audit one best.pt selected by the validation summary."""
    device = resolve_device("auto")
    checkpoint_path = str(run_row["checkpoint_path"])

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
        weights_only=False,
    )

    checkpoint_config = TrainingConfig.from_dict(
        checkpoint["config"]
    )

    expected_best_epoch = int(run_row["best_epoch"])
    checkpoint_epoch = int(checkpoint["epoch"])

    if checkpoint_epoch != expected_best_epoch:
        raise RuntimeError(
            "Checkpoint epoch does not match validation summary: "
            f"checkpoint={checkpoint_epoch}, "
            f"summary={expected_best_epoch}"
        )

    checkpoint_val_macro_f1 = float(
        checkpoint["metrics"]["val"]["macro_f1"]
    )
    expected_val_macro_f1 = float(
        run_row["best_val_macro_f1"]
    )

    if not np.isclose(
        checkpoint_val_macro_f1,
        expected_val_macro_f1,
        rtol=0.0,
        atol=1e-12,
    ):
        raise RuntimeError(
            "Checkpoint validation macro-F1 does not match summary: "
            f"checkpoint={checkpoint_val_macro_f1}, "
            f"summary={expected_val_macro_f1}"
        )


    model = build_resnet50(
        num_classes=checkpoint_config.num_classes,
        in_channels=checkpoint_config.in_channels,
        pretrained=False,
        input_mode=checkpoint_config.model_input_mode,
    ).to(device)

    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    print(
        f"Loaded {run_row['run_id']}: "
        f"best.pt epoch={checkpoint_epoch}, "
        f"val macro-F1={checkpoint_val_macro_f1:.6f}"
    )

    return model, checkpoint_config, device


def evaluate_under_fixed_mask(
    model,
    test_loader,
    device,
    condition,
):
    valid_conditions = {
        "CLEAN",
        "VISIBLE",
        "RED_EDGE_NIR",
        "ATMOSPHERIC",
        "SWIR",
    }

    if condition not in valid_conditions:
        raise ValueError(
            f"Unknown condition {condition!r}. "
            f"Expected one of {sorted(valid_conditions)}."
        )

    model.eval()
    y_true = []
    y_pred = []

    with torch.inference_mode():
        for images, labels in test_loader:
            images = images.to(
                device,
                non_blocking=True,
            ).float()

            if condition != "CLEAN":
                images = apply_fixed_group_mask(
                    images,
                    condition,
                )

            logits = model(images)
            predictions = logits.argmax(dim=1)

            y_true.extend(labels.tolist())
            y_pred.extend(predictions.cpu().tolist())

    labels = list(range(len(CLASS_NAMES)))

    accuracy = accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(
        y_true,
        y_pred,
        labels=labels,
        average="macro",
        zero_division=0,
    )
    per_class_values = f1_score(
        y_true,
        y_pred,
        labels=labels,
        average=None,
        zero_division=0,
    )

    return {
        "condition": condition,
        "accuracy": float(accuracy),
        "macro_f1": float(macro_f1),
        "per_class_f1": {
            class_name: float(class_f1)
            for class_name, class_f1 in zip(
                CLASS_NAMES,
                per_class_values,
            )
        },
        "num_samples": len(y_true),
    }

In [7]:
baseline_model, baseline_config, baseline_device = (
    load_best_model_from_row(baseline_row)
)

selected_model, selected_config, selected_device = (
    load_best_model_from_row(selected_row)
)

assert baseline_device == selected_device
assert baseline_config.modality == selected_config.modality == "ms"
assert baseline_config.split_type == selected_config.split_type == "spatial"
assert baseline_config.normalization == selected_config.normalization == "zscore"

set_seed(baseline_config.seed)

test_loader = build_test_dataloader(baseline_config)

print("Spatial test samples:", len(test_loader.dataset))
print("Test batches:", len(test_loader))

Loaded MS_SPATIAL_DROP_BASELINE: best.pt epoch=3, val macro-F1=0.938735
Loaded MS_SPATIAL_DROP_P05: best.pt epoch=19, val macro-F1=0.949802
Spatial test samples: 5400
Test batches: 169

In [8]:
import pandas as pd


TEST_CONDITIONS = [
    "CLEAN",
    "VISIBLE",
    "RED_EDGE_NIR",
    "ATMOSPHERIC",
    "SWIR",
]

MODEL_RUNS = [
    {
        "model_role": "baseline",
        "run_row": baseline_row,
        "model": baseline_model,
        "device": baseline_device,
    },
    {
        "model_role": "dropout_selected",
        "run_row": selected_row,
        "model": selected_model,
        "device": selected_device,
    },
]

test_summary_rows = []
test_class_rows = []

for model_run in MODEL_RUNS:
    model_role = model_run["model_role"]
    run_row = model_run["run_row"]
    model = model_run["model"]
    device = model_run["device"]

    for condition in TEST_CONDITIONS:
        print(
            f"Testing {run_row['run_id']} "
            f"under condition={condition}"
        )

        result = evaluate_under_fixed_mask(
            model=model,
            test_loader=test_loader,
            device=device,
            condition=condition,
        )

        test_summary_rows.append(
            {
                "model_role": model_role,
                "run_id": run_row["run_id"],
                "training_group_dropout_p": float(
                    run_row["group_dropout_p"]
                ),
                "selection_metric": (
                    "clean_spatial_validation_macro_f1"
                ),
                "selected_run_id": selected_row["run_id"],
                "selected_group_dropout_p": float(
                    selected_row["group_dropout_p"]
                ),
                "selected_val_macro_f1": float(
                    selected_row["best_val_macro_f1"]
                ),
                "test_condition": condition,
                "masked_group": (
                    "" if condition == "CLEAN" else condition
                ),
                "accuracy": result["accuracy"],
                "macro_f1": result["macro_f1"],
                "num_samples": result["num_samples"],
                "checkpoint_path": run_row["checkpoint_path"],
            }
        )

        for class_name, class_f1 in result[
            "per_class_f1"
        ].items():
            test_class_rows.append(
                {
                    "model_role": model_role,
                    "run_id": run_row["run_id"],
                    "training_group_dropout_p": float(
                        run_row["group_dropout_p"]
                    ),
                    "selected_run_id": selected_row["run_id"],
                    "selected_group_dropout_p": float(
                        selected_row["group_dropout_p"]
                    ),
                    "test_condition": condition,
                    "masked_group": (
                        "" if condition == "CLEAN" else condition
                    ),
                    "class_name": class_name,
                    "class_f1": class_f1,
                    "num_samples": result["num_samples"],
                    "checkpoint_path": run_row["checkpoint_path"],
                }
            )

print("All 10 test evaluations completed.")

Testing MS_SPATIAL_DROP_BASELINE under condition=CLEAN
Testing MS_SPATIAL_DROP_BASELINE under condition=VISIBLE
Testing MS_SPATIAL_DROP_BASELINE under condition=RED_EDGE_NIR
Testing MS_SPATIAL_DROP_BASELINE under condition=ATMOSPHERIC
Testing MS_SPATIAL_DROP_BASELINE under condition=SWIR
Testing MS_SPATIAL_DROP_P05 under condition=CLEAN
Testing MS_SPATIAL_DROP_P05 under condition=VISIBLE
Testing MS_SPATIAL_DROP_P05 under condition=RED_EDGE_NIR
Testing MS_SPATIAL_DROP_P05 under condition=ATMOSPHERIC
Testing MS_SPATIAL_DROP_P05 under condition=SWIR
All 10 test evaluations completed.

In [11]:
masked_metrics_df = pd.DataFrame(test_summary_rows)
per_class_f1_df = pd.DataFrame(test_class_rows)

clean_overall = (
    masked_metrics_df[
        masked_metrics_df["test_condition"] == "CLEAN"
    ][
        ["run_id", "accuracy", "macro_f1"]
    ]
    .rename(
        columns={
            "accuracy": "clean_accuracy",
            "macro_f1": "clean_macro_f1",
        }
    )
)

masked_metrics_df = masked_metrics_df.merge(
    clean_overall,
    on="run_id",
    how="left",
    validate="many_to_one",
)

masked_metrics_df["accuracy_drop_from_clean"] = (
    masked_metrics_df["clean_accuracy"]
    - masked_metrics_df["accuracy"]
)

masked_metrics_df["macro_f1_drop_from_clean"] = (
    masked_metrics_df["clean_macro_f1"]
    - masked_metrics_df["macro_f1"]
)


baseline_by_condition = (
    masked_metrics_df[
        masked_metrics_df["model_role"] == "baseline"
    ][
        [
            "test_condition",
            "accuracy",
            "macro_f1",
            "accuracy_drop_from_clean",
            "macro_f1_drop_from_clean",
        ]
    ]
    .rename(
        columns={
            "accuracy": "baseline_accuracy",
            "macro_f1": "baseline_macro_f1",
            "accuracy_drop_from_clean": (
                "baseline_accuracy_drop_from_clean"
            ),
            "macro_f1_drop_from_clean": (
                "baseline_macro_f1_drop_from_clean"
            ),
        }
    )
)

masked_metrics_df = masked_metrics_df.merge(
    baseline_by_condition,
    on="test_condition",
    how="left",
    validate="many_to_one",
)

masked_metrics_df["accuracy_vs_baseline"] = (
    masked_metrics_df["accuracy"]
    - masked_metrics_df["baseline_accuracy"]
)

masked_metrics_df["macro_f1_vs_baseline"] = (
    masked_metrics_df["macro_f1"]
    - masked_metrics_df["baseline_macro_f1"]
)

# Positive value means dropout reduced the damage caused by masking.
masked_metrics_df["macro_f1_drop_reduction_vs_baseline"] = (
    masked_metrics_df["baseline_macro_f1_drop_from_clean"]
    - masked_metrics_df["macro_f1_drop_from_clean"]
)


clean_per_class = (
    per_class_f1_df[
        per_class_f1_df["test_condition"] == "CLEAN"
    ][
        ["run_id", "class_name", "class_f1"]
    ]
    .rename(columns={"class_f1": "clean_class_f1"})
)

per_class_f1_df = per_class_f1_df.merge(
    clean_per_class,
    on=["run_id", "class_name"],
    how="left",
    validate="many_to_one",
)

per_class_f1_df["class_f1_drop_from_clean"] = (
    per_class_f1_df["clean_class_f1"]
    - per_class_f1_df["class_f1"]
)

baseline_class_by_condition = (
    per_class_f1_df[
        per_class_f1_df["model_role"] == "baseline"
    ][
        ["test_condition", "class_name", "class_f1"]
    ]
    .rename(columns={"class_f1": "baseline_class_f1"})
)

per_class_f1_df = per_class_f1_df.merge(
    baseline_class_by_condition,
    on=["test_condition", "class_name"],
    how="left",
    validate="many_to_one",
)

per_class_f1_df["class_f1_vs_baseline"] = (
    per_class_f1_df["class_f1"]
    - per_class_f1_df["baseline_class_f1"]
)

# Save formal artifacts
masked_metrics_path = resolve_project_path(
    "results/drop_out_experiment/masked_group_metrics.csv"
)
per_class_path = resolve_project_path(
    "results/drop_out_experiment/masked_group_per_class_f1.csv"
)

masked_metrics_df.to_csv(
    masked_metrics_path,
    index=False,
)

per_class_f1_df.to_csv(
    per_class_path,
    index=False,
)

print("Saved:", masked_metrics_path)
print("Saved:", per_class_path)

display(
    masked_metrics_df[
        [
            "model_role",
            "training_group_dropout_p",
            "test_condition",
            "accuracy",
            "macro_f1",
            "macro_f1_drop_from_clean",
            "macro_f1_vs_baseline",
            "macro_f1_drop_reduction_vs_baseline",
        ]
    ]
)

display(
    masked_metrics_df.pivot(
        index="test_condition",
        columns="model_role",
        values="macro_f1",
    ).loc[TEST_CONDITIONS]
)

Saved: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/results/masked_group_metrics.csv
Saved: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/results/masked_group_per_class_f1.csv

,model_role,training_group_dropout_p,test_condition,accuracy,macro_f1,macro_f1_drop_from_clean,macro_f1_vs_baseline,macro_f1_drop_reduction_vs_baseline
0,baseline,0.0,CLEAN,0.946852,0.916000,0.000000,0.000000,0.000000
1,baseline,0.0,VISIBLE,0.675556,0.522551,0.393450,0.000000,0.000000
2,baseline,0.0,RED_EDGE_NIR,0.877778,0.833462,0.082538,0.000000,0.000000
3,baseline,0.0,ATMOSPHERIC,0.942407,0.917179,-0.001179,0.000000,0.000000
4,baseline,0.0,SWIR,0.925000,0.900725,0.015276,0.000000,0.000000
5,dropout_selected,0.5,CLEAN,0.930370,0.896096,0.000000,-0.019904,0.000000
6,dropout_selected,0.5,VISIBLE,0.899444,0.838110,0.057987,0.315559,0.335463
7,dropout_selected,0.5,RED_EDGE_NIR,0.911296,0.876147,0.019950,0.042684,0.062588
8,dropout_selected,0.5,ATMOSPHERIC,0.930741,0.904918,-0.008822,-0.012261,0.007643
9,dropout_selected,0.5,SWIR,0.912963,0.869456,0.026640,-0.031269,-0.011365

model_role      baseline  dropout_selected
test_condition
CLEAN           0.916000          0.896096
VISIBLE         0.522551          0.838110
RED_EDGE_NIR    0.833462          0.876147
ATMOSPHERIC     0.917179          0.904918
SWIR            0.900725          0.869456

In [12]:
import pandas as pd

from satx.utils.paths import resolve_project_path


original_metrics_path = resolve_project_path(
    "results/drop_out_experiment/masked_group_metrics.csv"
)

raw_metrics_df = pd.read_csv(original_metrics_path)

assert len(raw_metrics_df) == 10
assert set(raw_metrics_df["model_role"]) == {
    "baseline",
    "dropout_selected",
}

TEST_CONDITION_ORDER = [
    "CLEAN",
    "VISIBLE",
    "RED_EDGE_NIR",
    "ATMOSPHERIC",
    "SWIR",
]

baseline_results = (
    raw_metrics_df[
        raw_metrics_df["model_role"] == "baseline"
    ]
    .set_index("test_condition")
    .loc[TEST_CONDITION_ORDER]
)

dropout_results = (
    raw_metrics_df[
        raw_metrics_df["model_role"] == "dropout_selected"
    ]
    .set_index("test_condition")
    .loc[TEST_CONDITION_ORDER]
)

comparison_numeric_df = pd.DataFrame(
    {
        "test_condition": TEST_CONDITION_ORDER,

        "baseline_accuracy": (
            baseline_results["accuracy"].to_numpy()
        ),
        "dropout_accuracy": (
            dropout_results["accuracy"].to_numpy()
        ),
        "accuracy_difference_pp": (
            (
                dropout_results["accuracy"].to_numpy()
                - baseline_results["accuracy"].to_numpy()
            )
            * 100
        ),

        "baseline_macro_f1": (
            baseline_results["macro_f1"].to_numpy()
        ),
        "dropout_macro_f1": (
            dropout_results["macro_f1"].to_numpy()
        ),
        "macro_f1_difference_pp": (
            (
                dropout_results["macro_f1"].to_numpy()
                - baseline_results["macro_f1"].to_numpy()
            )
            * 100
        ),

        "baseline_macro_f1_drop_pp": (
            baseline_results[
                "macro_f1_drop_from_clean"
            ].to_numpy()
            * 100
        ),
        "dropout_macro_f1_drop_pp": (
            dropout_results[
                "macro_f1_drop_from_clean"
            ].to_numpy()
            * 100
        ),
        "robustness_gain_pp": (
            (
                baseline_results[
                    "macro_f1_drop_from_clean"
                ].to_numpy()
                - dropout_results[
                    "macro_f1_drop_from_clean"
                ].to_numpy()
            )
            * 100
        ),
    }
)



comparison_display_df = comparison_numeric_df.copy()

score_columns = [
    "baseline_accuracy",
    "dropout_accuracy",
    "baseline_macro_f1",
    "dropout_macro_f1",
]

pp_columns = [
    "accuracy_difference_pp",
    "macro_f1_difference_pp",
    "baseline_macro_f1_drop_pp",
    "dropout_macro_f1_drop_pp",
    "robustness_gain_pp",
]

for column in score_columns:
    comparison_display_df[column] = (
        comparison_display_df[column]
        .map(lambda value: f"{value:.4f}")
    )

for column in pp_columns:
    comparison_display_df[column] = (
        comparison_display_df[column]
        .map(lambda value: f"{value:+.2f} pp")
    )

long_metrics_path = resolve_project_path(
    "results/drop_out_experiment/masked_group_metrics_long.csv"
)

raw_metrics_df.to_csv(
    long_metrics_path,
    index=False,
)


comparison_display_df.to_csv(
    original_metrics_path,
    index=False,
)


print("Saved compact comparison:", original_metrics_path)
print("Saved numeric long table:", long_metrics_path)

display(comparison_display_df)

Saved compact comparison: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/results/masked_group_metrics.csv
Saved numeric long table: /home/windhurt/dl_projects/projects/satx-eurosat-geographic-generalization-study/results/masked_group_metrics_long.csv

,test_condition,baseline_accuracy,dropout_accuracy,accuracy_difference_pp,baseline_macro_f1,dropout_macro_f1,macro_f1_difference_pp,baseline_macro_f1_drop_pp,dropout_macro_f1_drop_pp,robustness_gain_pp
0,CLEAN,0.9469,0.9304,-1.65 pp,0.9160,0.8961,-1.99 pp,+0.00 pp,+0.00 pp,+0.00 pp
1,VISIBLE,0.6756,0.8994,+22.39 pp,0.5226,0.8381,+31.56 pp,+39.34 pp,+5.80 pp,+33.55 pp
2,RED_EDGE_NIR,0.8778,0.9113,+3.35 pp,0.8335,0.8761,+4.27 pp,+8.25 pp,+1.99 pp,+6.26 pp
3,ATMOSPHERIC,0.9424,0.9307,-1.17 pp,0.9172,0.9049,-1.23 pp,-0.12 pp,-0.88 pp,+0.76 pp
4,SWIR,0.9250,0.9130,-1.20 pp,0.9007,0.8695,-3.13 pp,+1.53 pp,+2.66 pp,-1.14 pp